version: '3.8'

services:
  # Zookeeper service for Kafka
  zookeeper:
    image: zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181" # Expose Zookeeper port
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  # Kafka service
  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    ports:
      - "9092:9092" # Expose Kafka port
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181 # Connect Kafka to Zookeeper service
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092 # Advertised listeners for Kafka
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1 # Set replication factor to 1 for development
    depends_on:
      - zookeeper # Ensure Zookeeper starts before Kafka

  # CommentService microservice
  commentService:
    build:
      context: ./CommentService
      dockerfile: Dockerfile
    container_name: commentService
    ports:
      - '8000:8000' # Map port 8000 on the host to port 8000 in the container

  # TaskService microservice
  taskService:
    build:
      context: ./TaskService
      dockerfile: Dockerfile
    container_name: taskService
    ports:
      - '8002:8002' # Map port 8002 on the host to port 8002 in the container

  # UserService microservice
  userService:
    build:
      context: ./UserService
      dockerfile: Dockerfile
    container_name: userService
    ports:
      - '8001:8001' # Map port 8001 on the host to port 8001 in the container

  # Nginx proxy service
  nginx-proxy:
    build:
      context: ./nginx-docker
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - commentService
      - taskService
      - userService
