#!/bin/bash

# Define variables
KAFKA_CONTAINER_NAME="kafka"
KAFKA_PORT="9092"
ZOOKEEPER_CONNECT="127.0.0.1:2181"
KAFKA_ADVERTISED_LISTENER="PLAINTEXT://127.0.0.1:$KAFKA_PORT"
REPLICATION_FACTOR="1"

# Run the Kafka container
docker run --name $KAFKA_CONTAINER_NAME \
           -p $KAFKA_PORT:$KAFKA_PORT \
           -e KAFKA_ZOOKEEPER_CONNECT=$ZOOKEEPER_CONNECT \
           -e KAFKA_ADVERTISED_LISTENERS=$KAFKA_ADVERTISED_LISTENER \
           -e KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=$REPLICATION_FACTOR \
           confluentinc/cp-kafka
